# This is a basic workflow to help you get started with Actions

name: DEV

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - name: apt update
        run: sudo apt update
      - name: install git
        run: sudo apt install git
      - name: check git version
        run: git --version
      - name: add username
        run: git config --global user.name "simonezardi"
      - name: add email
        run: git config --global user.email "simone.zardi@storci.com"
      - name: add remote
        run: git remote add dev https://$username:$repo_key@github.com/sz-multiple-enviroment/dev.git
        env:
          repo_key: ${{ secrets.API_TOKEN_GITHUB }}
          username: simonezardi
      - name: add remote
        run: git fetch --unshallow dev
      - name: check remote
        run: git remote -v
      - name: check branches
        run: git branch
      - name: checkout branch dev
        run: git checkout dev
      - name: push to dev repository
        run: git push https://$username:$repo_key@github.com/sz-multiple-enviroment/dev.git dev:main --force
        env:
          repo_key: ${{ secrets.API_TOKEN_GITHUB }}
          username: simonezardi
